---
- name: Check if deploy_share_before scripts exist
  ansible.builtin.stat:
    path: "{{ item }}"
  delegate_to: localhost
  register: deploy_share_before_paths
  loop: "{{ deploy_share_before | default([]) }}"

- name: Include deploy_share_before tasks
  ansible.builtin.include_tasks: "{{ include_path.item }}"
  loop: "{{ deploy_share_before_paths.results }}"
  loop_control:
    loop_var: include_path
    label: "{{ include_path.item }}"
  when: include_path.stat.exists
  tags: deploy-share-before

- name: Ensure shared sources are present -- directories
  ansible.builtin.file:
    path: "{{ deploy_helper.shared_path }}/{{ item.src }}"
    state: directory
    mode: "{{ item.mode | default('0755') }}"
  loop: "{{ project.project_shared_children | default(project_shared_children) }}"
  loop_control:
    label: "{{ item.path }}"
  when: item.type | default('directory') | lower == 'directory'

- name: Ensure shared sources are present -- files' parent directories
  ansible.builtin.file:
    path: "{{ deploy_helper.shared_path }}/{{ item.src | dirname }}"
    state: directory
    mode: '0755'
  loop: "{{ project.project_shared_children | default(project_shared_children) }}"
  loop_control:
    label: "{{ item.path }}"
  when: item.type | default('directory') | lower == 'file'

- name: Ensure shared sources are present -- files
  ansible.builtin.file:
    path: "{{ deploy_helper.shared_path }}/{{ item.src }}"
    state: touch
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ project.project_shared_children | default(project_shared_children) }}"
  loop_control:
    label: "{{ item.path }}"
  when: item.type | default('directory') | lower == 'file'

- name: Ensure parent directories for shared paths are present
  ansible.builtin.file:
    path: "{{ deploy_helper.new_release_path }}/{{ item.path | dirname }}"
    mode: '0755'
    state: directory
  loop: "{{ project.project_shared_children | default(project_shared_children) }}"
  loop_control:
    label: "{{ item.path }}"

- name: Ensure shared paths are absent
  ansible.builtin.file:
    path: "{{ deploy_helper.new_release_path }}/{{ item.path }}"
    state: absent
  loop: "{{ project.project_shared_children | default(project_shared_children) }}"
  loop_control:
    label: "{{ item.path }}"

- name: Create shared symlinks
  ansible.builtin.file:
    path: "{{ deploy_helper.new_release_path }}/{{ item.path }}"
    src: "{{ deploy_helper.shared_path }}/{{ item.src }}"
    state: link
  loop: "{{ project.project_shared_children | default(project_shared_children) }}"
  loop_control:
    label: "{{ item.path }}"

- name: Check if deploy_share_after scripts exist
  ansible.builtin.stat:
    path: "{{ item }}"
  delegate_to: localhost
  register: deploy_share_after_paths
  loop: "{{ deploy_share_after | default([]) }}"

- name: Include deploy_share_after tasks
  ansible.builtin.include_tasks: "{{ include_path.item }}"
  loop: "{{ deploy_share_after_paths.results }}"
  loop_control:
    loop_var: include_path
    label: "{{ include_path.item }}"
  when: include_path.stat.exists
  tags: deploy-share-after
